language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sugar' ]; then cd .. && eval "mv $currentfolder generator-sugar" && cd generator-sugar; fi

